name: Daily Commit

on:
  schedule:
    - cron: '30 8 * * *' # runs daily at 08:30 UTC
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        # persist-credentials defaults to true

      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
        
      - name: Commit and push changes
        run: |
          echo "Daily commit $(date)" >> daily_commit.txt
          git add daily_commit.txt
          git commit -m "Daily commit $(date)" || echo "No changes to commit"
          git push
